#!/usr/bin/env php
<?php

defined('YII_DEBUG') or define('YII_DEBUG', getenv('YII_DEBUG') ?: false);
defined('YII_ENV') or define('YII_ENV', getenv('YII_ENV') ?: 'prod');

$baseDir = __DIR__ . DIRECTORY_SEPARATOR;
/** @var Composer\Autoload\ClassLoader $composerAutoload */
$composerAutoload = require $baseDir . 'vendor/autoload.php';
require $baseDir . 'vendor/yiisoft/yii2/Yii.php';

$application = new yii\console\Application(require $baseDir . 'config/console.php');
exit($application->run());
