#!/usr/bin/env php
<?php
defined('YII_DEBUG') || define('YII_DEBUG', true);
defined('YII_ENV') || define('YII_ENV', 'dev');

$appDir = __DIR__;

require($appDir . '/vendor/yiisoft/yii2/Yii.php');
require($appDir . '/vendor/autoload.php');

$application = new yii\console\Application(require($appDir . '/config/console.php'));
exit($application->run());
